import { describe, expect, it } from "vitest";
import { getPeriodBounds } from "../src/date";
import {
  createSavedSummaryDescriptor,
  getSavedSummaryState,
  isGeneratedTallySummary
} from "../src/saved-summary";
import type {
  AggregateTaskSource,
  DailyMetricSource,
  PeriodAggregate,
  PeriodMode,
  PlainDate
} from "../src/types";

function source(isoDate: string, value: number): DailyMetricSource {
  const [year, month, day] = isoDate.split("-").map(Number) as [number, number, number];
  return {
    date: { year, month, day },
    isoDate,
    path: `Journal/${year}/${String(month).padStart(2, "0")}/${isoDate}.md`,
    value
  };
}

function taskSource(isoDate: string, tag: string, value: number): AggregateTaskSource {
  return {
    ...source(isoDate, value),
    tag,
    text: `${value} #${tag}`,
    line: 3
  };
}

function aggregate(mode: PeriodMode, anchor: PlainDate, notePaths: string[]): PeriodAggregate {
  const noteSources = notePaths.map((path) => {
    const isoDate = path.match(/(\d{4}-\d{2}-\d{2})\.md$/u)?.[1];
    if (!isoDate) throw new Error(`Missing date in ${path}`);
    return source(isoDate, 1);
  });
  return {
    bounds: getPeriodBounds(anchor, mode, 1),
    noteCount: notePaths.length,
    notePaths,
    noteSources,
    words: 44,
    photos: 3,
    totalCheckboxes: 3,
    completedCheckboxes: 2,
    wordSources: [],
    photoSources: [],
    checkboxSources: [],
    tags: [
      { tag: "greek", total: 1, sources: [] },
      { tag: "pushups", total: 160, sources: [] }
    ]
  };
}

describe("saved summaries", () => {
  it("uses the common daily-note folder instead of assuming a date layout", () => {
    const year = createSavedSummaryDescriptor("Journal", "year", aggregate("year", {
      year: 2026, month: 8, day: 12
    }, ["Journal/2026/01/2026-01-02.md", "Journal/2026/08/2026-08-12.md"]), 1, "en-US");
    const month = createSavedSummaryDescriptor("Journal", "month", aggregate("month", {
      year: 2026, month: 8, day: 12
    }, ["Journal/2026/08/2026-08-01.md", "Journal/2026/08/2026-08-12.md"]), 1, "en-US");
    const flat = createSavedSummaryDescriptor("Journal", "week", aggregate("week", {
      year: 2026, month: 8, day: 12
    }, ["Journal/2026-08-10.md", "Journal/2026-08-12.md"]), 1, "en-US");
    const vaultRoot = createSavedSummaryDescriptor("", "month", aggregate("month", {
      year: 2026, month: 8, day: 12
    }, ["2026/08/2026-08-10.md", "2026/08/2026-08-12.md"]), 1, "en-US");

    expect(year.path).toBe("Journal/2026/Tally — 2026.md");
    expect(month.path).toBe("Journal/2026/08/Tally — 2026-08.md");
    expect(flat.path).toBe("Journal/Tally — 2026-08-10 to 2026-08-16.md");
    expect(vaultRoot.path).toBe("2026/08/Tally — 2026-08.md");
  });

  it("serializes a natural overview, chronological activity and tally tables, and writing highlight", () => {
    const data = aggregate("year", { year: 2026, month: 8, day: 12 }, [
      "Journal/2026/01/2026-01-02.md",
      "Journal/2026/02/2026-02-01.md"
    ]);
    data.wordSources = [source("2026-01-02", 10), source("2026-02-01", 34)];
    data.photoSources = [source("2026-01-02", 1), source("2026-02-01", 2)];
    data.checkboxSources = [source("2026-01-02", 1), source("2026-02-01", 1)];
    data.tags = [
      { tag: "greek", total: 1, sources: [taskSource("2026-02-01", "greek", 1)] },
      { tag: "pushups", total: 160, sources: [taskSource("2026-01-02", "pushups", 160)] }
    ];

    const summary = createSavedSummaryDescriptor("Journal", "year", data, 1, "en-US");
    expect(summary.content).toBe([
      "## At a glance",
      "",
      "**Daily notes: 2 of 365 days** · **Words: 44** · **Photos: 3** · **Checked items: 2 of 3**",
      "",
      "**Tallies:** Greek 1 · Pushups 160",
      "",
      "**Most writing:** [[Journal/2026/02/2026-02-01|Sun, Feb 1]] · 34 words",
      "",
      "## Months",
      "",
      "| Month | Daily notes | Words | Photos | Checked items |",
      "| --- | ---: | ---: | ---: | ---: |",
      "| Jan | 1 | 10 | 1 | 1 |",
      "| Feb | 1 | 34 | 2 | 1 |",
      "",
      "## Tallies by month",
      "",
      "| Month | Greek | Pushups |",
      "| --- | ---: | ---: |",
      "| Jan | — | 160 |",
      "| Feb | 1 | — |",
      "",
      "<!-- daymark-tally-report:v2 -->",
      ""
    ].join("\n"));
    expect(summary.content).not.toContain("# Tally");
    expect(summary.content).not.toContain("Generated by Tally");
    expect(summary.content).not.toContain("Greek 0");
    expect(summary.content).not.toContain("Pushups 0");
  });

  it("links daily notes from Week breakdowns", () => {
    const data = aggregate("week", { year: 2026, month: 8, day: 12 }, [
      "Journal/2026/08/2026-08-12.md"
    ]);
    data.wordSources = [source("2026-08-12", 44)];
    const summary = createSavedSummaryDescriptor("Journal", "week", data, 1, "en-US");
    expect(summary.content).toContain("| [[Journal/2026/08/2026-08-12\\|Wed, Aug 12]] | 1 | 44 | 0 | 0 |");
    expect(summary.content).toContain("**Most writing:** [[Journal/2026/08/2026-08-12|Wed, Aug 12]] · 44 words");
  });

  it("keeps zero-valued tallies when a checked item explicitly records zero", () => {
    const data = aggregate("week", { year: 2026, month: 8, day: 12 }, [
      "Journal/2026/08/2026-08-12.md"
    ]);
    data.tags = [
      { tag: "stillness", total: 0, sources: [taskSource("2026-08-12", "stillness", 0)] }
    ];

    const summary = createSavedSummaryDescriptor("Journal", "week", data, 1, "en-US");
    expect(summary.content).toContain("**Tallies:** Stillness 0");
    expect(summary.content).toContain("## Tallies by day");
    expect(summary.content).toContain(
      "| [[Journal/2026/08/2026-08-12\\|Wed, Aug 12]] | 0 |"
    );
  });

  it("uses escaped aliases in totals and every breakdown while keeping duplicate labels separate", () => {
    const data = aggregate("week", { year: 2026, month: 8, day: 12 }, [
      "Journal/2026/08/2026-08-12.md"
    ]);
    data.tags = [
      { tag: "pushups", total: 100, sources: [taskSource("2026-08-12", "pushups", 100)] },
      { tag: "running", total: 6, sources: [taskSource("2026-08-12", "running", 6)] }
    ];
    const labels = {
      pushups: "Effort *done*",
      running: "Effort *done*"
    };

    const summary = createSavedSummaryDescriptor("Journal", "week", data, 1, "en-US", labels);
    expect(summary.content).toContain("**Tallies:** Effort \\*done\\* 100 · Effort \\*done\\* 6");
    expect(summary.content).toContain("| Day | Effort \\*done\\* | Effort \\*done\\* |");
    expect(summary.content).toContain("| [[Journal/2026/08/2026-08-12\\|Wed, Aug 12]] | 100 | 6 |");
  });

  it("marks an existing generated report stale when an alias changes", () => {
    const data = aggregate("week", { year: 2026, month: 8, day: 12 }, [
      "Journal/2026/08/2026-08-12.md"
    ]);
    const first = createSavedSummaryDescriptor("Journal", "week", data, 1, "en-US", {
      pushups: "Push-ups completed"
    });
    const changed = createSavedSummaryDescriptor("Journal", "week", data, 1, "en-US", {
      pushups: "Repetitions"
    });
    expect(getSavedSummaryState(first.content, changed.content)).toBe("update");
  });

  it("uses core metric aliases and marks their report stale when they change", () => {
    const data = aggregate("week", { year: 2026, month: 8, day: 12 }, [
      "Journal/2026/08/2026-08-12.md"
    ]);
    const first = createSavedSummaryDescriptor("Journal", "week", data, 1, "en-US", {}, {
      dailyNotes: "Journal days",
      words: "Writing",
      photos: "Images"
    });
    expect(first.content).toContain("**Journal days: 1 of 7 days** · **Writing: 44** · **Images: 3**");
    expect(first.content).toContain("| Day | Journal days | Writing | Images | Checked items |");
    const changed = createSavedSummaryDescriptor("Journal", "week", data, 1, "en-US", {}, {
      dailyNotes: "Entries",
      words: "Writing",
      photos: "Images"
    });
    expect(getSavedSummaryState(first.content, changed.content)).toBe("update");
  });

  it("recognizes current and legacy generated summaries but rejects ordinary notes", () => {
    const legacyMarker = "<!-- Generated by Tally. Saving this period again replaces this file. -->";
    const current = "## At a glance\n\n**1 of 7 days** · **10 words**\n\n<!-- daymark-tally-report:v2 -->\n";
    expect(isGeneratedTallySummary(current)).toBe(true);
    expect(isGeneratedTallySummary(`${legacyMarker}\n# Tally — 2026\n\n- **Words:** 1\n`)).toBe(true);
    expect(isGeneratedTallySummary("# Tally — 2026\n\n- **Words:** 1\n- **Checked:** 0\n")).toBe(true);
    expect(isGeneratedTallySummary("## Totals\n\n- **Words:** 1\n\n## Breakdown\n\n### Words\n\n- **January:** 1\n")).toBe(true);
    expect(isGeneratedTallySummary("## At a glance\n\nMy own notes\n")).toBe(false);
    expect(isGeneratedTallySummary("## Totals\n\nMy own notes\n")).toBe(false);
  });

  it("distinguishes unsaved, current, and stale generated summaries", () => {
    const expected = "## Totals\n\n- **Daily notes:** 1\n- **Words:** 10\n";
    expect(getSavedSummaryState(null, expected)).toBe("save");
    expect(getSavedSummaryState(expected, expected)).toBe("saved");
    expect(getSavedSummaryState(`${expected}\n`, expected)).toBe("saved");
    expect(getSavedSummaryState("## Totals\n\n- **Daily notes:** 1\n- **Words:** 9\n", expected)).toBe("update");
    expect(getSavedSummaryState("My own note\n", expected)).toBe("save");
  });
});
