import { describe, expect, it } from "vitest";
import { getPeriodBounds } from "../src/date";
import {
  createSavedSummaryDescriptor,
  getSavedSummaryState,
  isGeneratedTallySummary
} from "../src/saved-summary";
import type {
  AggregateTaskSource,
  DailyMetricSource,
  PeriodAggregate,
  PeriodMode,
  PlainDate
} from "../src/types";

function source(isoDate: string, value: number): DailyMetricSource {
  const [year, month, day] = isoDate.split("-").map(Number) as [number, number, number];
  return {
    date: { year, month, day },
    isoDate,
    path: `Journal/${year}/${String(month).padStart(2, "0")}/${isoDate}.md`,
    value
  };
}

function taskSource(isoDate: string, tag: string, value: number): AggregateTaskSource {
  return {
    ...source(isoDate, value),
    tag,
    text: `${value} #${tag}`,
    line: 3
  };
}

function aggregate(mode: PeriodMode, anchor: PlainDate, notePaths: string[]): PeriodAggregate {
  const noteSources = notePaths.map((path) => {
    const isoDate = path.match(/(\d{4}-\d{2}-\d{2})\.md$/u)?.[1];
    if (!isoDate) throw new Error(`Missing date in ${path}`);
    return source(isoDate, 1);
  });
  return {
    bounds: getPeriodBounds(anchor, mode, 1),
    noteCount: notePaths.length,
    notePaths,
    noteSources,
    words: 44,
    totalCheckboxes: 3,
    completedCheckboxes: 2,
    wordSources: [],
    checkboxSources: [],
    tags: [
      { tag: "greek", total: 1, sources: [] },
      { tag: "pushups", total: 160, sources: [] }
    ]
  };
}

describe("saved summaries", () => {
  it("uses the common daily-note folder instead of assuming a date layout", () => {
    const year = createSavedSummaryDescriptor("Journal", "year", aggregate("year", {
      year: 2026, month: 8, day: 12
    }, ["Journal/2026/01/2026-01-02.md", "Journal/2026/08/2026-08-12.md"]), 1, "en-US");
    const month = createSavedSummaryDescriptor("Journal", "month", aggregate("month", {
      year: 2026, month: 8, day: 12
    }, ["Journal/2026/08/2026-08-01.md", "Journal/2026/08/2026-08-12.md"]), 1, "en-US");
    const flat = createSavedSummaryDescriptor("Journal", "week", aggregate("week", {
      year: 2026, month: 8, day: 12
    }, ["Journal/2026-08-10.md", "Journal/2026-08-12.md"]), 1, "en-US");
    const vaultRoot = createSavedSummaryDescriptor("", "month", aggregate("month", {
      year: 2026, month: 8, day: 12
    }, ["2026/08/2026-08-10.md", "2026/08/2026-08-12.md"]), 1, "en-US");

    expect(year.path).toBe("Journal/2026/Tally — 2026.md");
    expect(month.path).toBe("Journal/2026/08/Tally — 2026-08.md");
    expect(flat.path).toBe("Journal/Tally — 2026-08-10 to 2026-08-16.md");
    expect(vaultRoot.path).toBe("2026/08/Tally — 2026-08.md");
  });

  it("serializes totals and period breakdowns without repeating the filename title", () => {
    const data = aggregate("year", { year: 2026, month: 8, day: 12 }, [
      "Journal/2026/01/2026-01-02.md",
      "Journal/2026/02/2026-02-01.md"
    ]);
    data.wordSources = [source("2026-01-02", 10), source("2026-02-01", 34)];
    data.checkboxSources = [source("2026-01-02", 1), source("2026-02-01", 1)];
    data.tags = [
      { tag: "greek", total: 1, sources: [taskSource("2026-02-01", "greek", 1)] },
      { tag: "pushups", total: 160, sources: [taskSource("2026-01-02", "pushups", 160)] }
    ];

    const summary = createSavedSummaryDescriptor("Journal", "year", data, 1, "en-US");
    expect(summary.content).toBe([
      "## Totals",
      "",
      "- **Daily notes:** 2",
      "- **Words:** 44",
      "- **Checked items:** 2",
      "- **Greek:** 1",
      "- **Pushups:** 160",
      "",
      "## Breakdown",
      "",
      "### Feb",
      "",
      "- **Daily notes:** 1",
      "- **Words:** 34",
      "- **Checked items:** 1",
      "- **Greek:** 1",
      "- **Pushups:** 0",
      "",
      "### Jan",
      "",
      "- **Daily notes:** 1",
      "- **Words:** 10",
      "- **Checked items:** 1",
      "- **Greek:** 0",
      "- **Pushups:** 160",
      ""
    ].join("\n"));
    expect(summary.content).not.toContain("# Tally");
    expect(summary.content).not.toContain("Generated by Tally");
  });

  it("links daily notes from Week breakdowns", () => {
    const data = aggregate("week", { year: 2026, month: 8, day: 12 }, [
      "Journal/2026/08/2026-08-12.md"
    ]);
    data.wordSources = [source("2026-08-12", 44)];
    const summary = createSavedSummaryDescriptor("Journal", "week", data, 1, "en-US");
    expect(summary.content).toContain("[[Journal/2026/08/2026-08-12|Wed, Aug 12]]");
  });

  it("recognizes current and legacy generated summaries but rejects ordinary notes", () => {
    const legacyMarker = "<!-- Generated by Tally. Saving this period again replaces this file. -->";
    expect(isGeneratedTallySummary(`${legacyMarker}\n# Tally — 2026\n\n- **Words:** 1\n`)).toBe(true);
    expect(isGeneratedTallySummary("# Tally — 2026\n\n- **Words:** 1\n- **Checked:** 0\n")).toBe(true);
    expect(isGeneratedTallySummary("## Totals\n\n- **Words:** 1\n\n## Breakdown\n\n### Words\n\n- **January:** 1\n")).toBe(true);
    expect(isGeneratedTallySummary("## Totals\n\nMy own notes\n")).toBe(false);
  });

  it("distinguishes unsaved, current, and stale generated summaries", () => {
    const expected = "## Totals\n\n- **Daily notes:** 1\n- **Words:** 10\n";
    expect(getSavedSummaryState(null, expected)).toBe("save");
    expect(getSavedSummaryState(expected, expected)).toBe("saved");
    expect(getSavedSummaryState(`${expected}\n`, expected)).toBe("saved");
    expect(getSavedSummaryState("## Totals\n\n- **Daily notes:** 1\n- **Words:** 9\n", expected)).toBe("update");
    expect(getSavedSummaryState("My own note\n", expected)).toBe("save");
  });
});
