import { addDays, toIsoDate } from "./date";
import { buildBreakdownRows, type BreakdownSource } from "./drilldown";
import { formatTagLabel } from "./format";
import type { PeriodAggregate, PeriodMode, Weekday } from "./types";

const LEGACY_GENERATED_SUMMARY_MARKER = "<!-- Generated by Tally. Saving this period again replaces this file. -->";

export interface SavedSummaryDescriptor {
  folder: string;
  path: string;
  content: string;
}

export type SavedSummaryState = "save" | "saved" | "update";

function normalizeVaultPath(value: string): string {
  return value.trim().replace(/\\/gu, "/").replace(/\/{2,}/gu, "/").replace(/^\/+|\/+$/gu, "");
}

function joinVaultPath(...parts: string[]): string {
  return parts.filter((part) => part.length > 0).join("/").replace(/\/{2,}/gu, "/");
}

function parentFolder(path: string): string {
  const normalized = normalizeVaultPath(path);
  const separator = normalized.lastIndexOf("/");
  return separator < 0 ? "" : normalized.slice(0, separator);
}

function commonFolder(paths: string[], fallback: string): string {
  if (paths.length === 0) return normalizeVaultPath(fallback);
  const parents = paths.map((path) => parentFolder(path).split("/").filter(Boolean));
  const first = parents[0] ?? [];
  let length = first.length;
  for (const segments of parents.slice(1)) {
    let shared = 0;
    while (shared < length && first[shared] === segments[shared]) shared += 1;
    length = shared;
  }
  const candidate = first.slice(0, length).join("/");
  const root = normalizeVaultPath(fallback);
  if (root.length === 0) return candidate;
  return candidate === root || candidate.startsWith(`${root}/`) ? candidate : root;
}

function summaryKey(mode: PeriodMode, aggregate: PeriodAggregate): string {
  if (mode === "year") return String(aggregate.bounds.start.year);
  if (mode === "month") {
    return `${aggregate.bounds.start.year}-${String(aggregate.bounds.start.month).padStart(2, "0")}`;
  }
  const last = addDays(aggregate.bounds.end, -1);
  return `${toIsoDate(aggregate.bounds.start)} to ${toIsoDate(last)}`;
}

export function isGeneratedTallySummary(content: string): boolean {
  const normalized = content.replace(/\r\n/gu, "\n").trimEnd();
  if (normalized.startsWith(LEGACY_GENERATED_SUMMARY_MARKER)) return true;

  const lines = normalized.split("\n");
  if (lines[0]?.startsWith("# Tally — ") && lines[1] === "" && lines.length >= 3) {
    return lines.slice(2).every((line) => /^- \*\*[^*\n]+:\*\* .+$/u.test(line));
  }
  if (lines[0] !== "## Totals") return false;
  const allowed = /^(?:|## Breakdown|### .+|- \*\*.+:\*\* .+)$/u;
  return lines.slice(1).every((line) => allowed.test(line))
    && lines.some((line) => /^- \*\*.+:\*\* .+$/u.test(line));
}

function normalizeSummaryContent(content: string): string {
  return content.replace(/\r\n?/gu, "\n").trimEnd();
}

export function getSavedSummaryState(
  existingContent: string | null,
  expectedContent: string
): SavedSummaryState {
  if (existingContent === null) return "save";
  if (normalizeSummaryContent(existingContent) === normalizeSummaryContent(expectedContent)) return "saved";
  return isGeneratedTallySummary(existingContent) ? "update" : "save";
}

function breakdownLabel(label: string, path: string | null): string {
  if (!path) return label;
  return `[[${path.replace(/\.md$/u, "")}|${label}]]`;
}

function breakdownValues(
  sources: BreakdownSource[],
  mode: PeriodMode,
  aggregate: PeriodAggregate,
  weekStart: Weekday,
  locale: string | undefined
): Map<string, number> {
  const rows = buildBreakdownRows(sources, mode, aggregate.bounds, weekStart, locale);
  return new Map(rows.map((row) => [row.key, row.value]));
}

export function createSavedSummaryDescriptor(
  journalFolder: string,
  mode: PeriodMode,
  aggregate: PeriodAggregate,
  weekStart: Weekday,
  locale?: string
): SavedSummaryDescriptor {
  const folder = commonFolder(aggregate.notePaths, journalFolder);
  const filename = `Tally — ${summaryKey(mode, aggregate)}.md`;
  const formatNumber = (value: number) => new Intl.NumberFormat(locale, { maximumFractionDigits: 3 }).format(value);
  const lines = [
    "## Totals",
    "",
    `- **Daily notes:** ${formatNumber(aggregate.noteCount)}`,
    `- **Words:** ${formatNumber(aggregate.words)}`,
    `- **Checked items:** ${formatNumber(aggregate.completedCheckboxes)}`,
    ...aggregate.tags.map((tag) => `- **${formatTagLabel(tag.tag, locale)}:** ${formatNumber(tag.total)}`)
  ];
  const periods = buildBreakdownRows(
    aggregate.noteSources,
    mode,
    aggregate.bounds,
    weekStart,
    locale
  );
  const words = breakdownValues(aggregate.wordSources, mode, aggregate, weekStart, locale);
  const checked = breakdownValues(aggregate.checkboxSources, mode, aggregate, weekStart, locale);
  const tagged = aggregate.tags.map((tag) => ({
    label: formatTagLabel(tag.tag, locale),
    values: breakdownValues(tag.sources, mode, aggregate, weekStart, locale)
  }));
  if (periods.length > 0) {
    lines.push("", "## Breakdown");
    for (const period of periods) {
      lines.push(
        "",
        `### ${breakdownLabel(period.label, period.path)}`,
        "",
        `- **Daily notes:** ${formatNumber(period.value)}`,
        `- **Words:** ${formatNumber(words.get(period.key) ?? 0)}`,
        `- **Checked items:** ${formatNumber(checked.get(period.key) ?? 0)}`,
        ...tagged.map((tag) => `- **${tag.label}:** ${formatNumber(tag.values.get(period.key) ?? 0)}`)
      );
    }
  }
  lines.push("");

  return {
    folder,
    path: joinVaultPath(folder, filename),
    content: lines.join("\n")
  };
}
