import { periodDayCount } from "./calendar-summary";
import { addDays, formatBreakdownDay, toIsoDate } from "./date";
import { buildBreakdownRows, sumBreakdownValues, type BreakdownSource } from "./drilldown";
import { formatTagLabel } from "./format";
import { numberFormatter } from "./intl-cache";
import type { PeriodAggregate, PeriodMode, Weekday } from "./types";

const LEGACY_GENERATED_SUMMARY_MARKER = "<!-- Generated by Tally. Saving this period again replaces this file. -->";
const GENERATED_SUMMARY_MARKER = "<!-- daymark-tally-report:v2 -->";

export interface SavedSummaryDescriptor {
  folder: string;
  path: string;
  content: string;
}

export type SavedSummaryState = "save" | "saved" | "update";

const REPORT_PERIOD_COPY: Record<PeriodMode, {
  heading: string;
  column: string;
  tallyHeading: string;
}> = {
  week: { heading: "Days", column: "Day", tallyHeading: "Tallies by day" },
  month: { heading: "Weeks", column: "Week", tallyHeading: "Tallies by week" },
  year: { heading: "Months", column: "Month", tallyHeading: "Tallies by month" }
};

function normalizeVaultPath(value: string): string {
  return value.trim().replace(/\\/gu, "/").replace(/\/{2,}/gu, "/").replace(/^\/+|\/+$/gu, "");
}

function joinVaultPath(...parts: string[]): string {
  return parts.filter((part) => part.length > 0).join("/").replace(/\/{2,}/gu, "/");
}

function parentFolder(path: string): string {
  const normalized = normalizeVaultPath(path);
  const separator = normalized.lastIndexOf("/");
  return separator < 0 ? "" : normalized.slice(0, separator);
}

function commonFolder(paths: string[], fallback: string): string {
  if (paths.length === 0) return normalizeVaultPath(fallback);
  const parents = paths.map((path) => parentFolder(path).split("/").filter(Boolean));
  const first = parents[0] ?? [];
  let length = first.length;
  for (const segments of parents.slice(1)) {
    let shared = 0;
    while (shared < length && first[shared] === segments[shared]) shared += 1;
    length = shared;
  }
  const candidate = first.slice(0, length).join("/");
  const root = normalizeVaultPath(fallback);
  if (root.length === 0) return candidate;
  return candidate === root || candidate.startsWith(`${root}/`) ? candidate : root;
}

function summaryKey(mode: PeriodMode, aggregate: PeriodAggregate): string {
  if (mode === "year") return String(aggregate.bounds.start.year);
  if (mode === "month") {
    return `${aggregate.bounds.start.year}-${String(aggregate.bounds.start.month).padStart(2, "0")}`;
  }
  const last = addDays(aggregate.bounds.end, -1);
  return `${toIsoDate(aggregate.bounds.start)} to ${toIsoDate(last)}`;
}

export function isGeneratedTallySummary(content: string): boolean {
  const normalized = content.replace(/\r\n/gu, "\n").trimEnd();
  if (normalized.startsWith(LEGACY_GENERATED_SUMMARY_MARKER)) return true;

  const lines = normalized.split("\n");
  if (lines[0] === "## At a glance" && lines[lines.length - 1] === GENERATED_SUMMARY_MARKER) return true;
  if (lines[0]?.startsWith("# Tally — ") && lines[1] === "" && lines.length >= 3) {
    return lines.slice(2).every((line) => /^- \*\*[^*\n]+:\*\* .+$/u.test(line));
  }
  if (lines[0] !== "## Totals") return false;
  const allowed = /^(?:|## Breakdown|### .+|- \*\*.+:\*\* .+)$/u;
  return lines.slice(1).every((line) => allowed.test(line))
    && lines.some((line) => /^- \*\*.+:\*\* .+$/u.test(line));
}

function normalizeSummaryContent(content: string): string {
  return content.replace(/\r\n?/gu, "\n").trimEnd();
}

export function getSavedSummaryState(
  existingContent: string | null,
  expectedContent: string
): SavedSummaryState {
  if (existingContent === null) return "save";
  if (normalizeSummaryContent(existingContent) === normalizeSummaryContent(expectedContent)) return "saved";
  return isGeneratedTallySummary(existingContent) ? "update" : "save";
}

function breakdownLabel(label: string, path: string | null, tableCell = false): string {
  if (!path) return label;
  const separator = tableCell ? "\\|" : "|";
  return `[[${path.replace(/\.md$/u, "")}${separator}${label}]]`;
}

export function createSavedSummaryDescriptor(
  journalFolder: string,
  mode: PeriodMode,
  aggregate: PeriodAggregate,
  weekStart: Weekday,
  locale?: string
): SavedSummaryDescriptor {
  const folder = commonFolder(aggregate.notePaths, journalFolder);
  const filename = `Tally — ${summaryKey(mode, aggregate)}.md`;
  const number = numberFormatter(locale, { maximumFractionDigits: 3 });
  const formatNumber = (value: number) => number.format(value);
  const periodCopy = REPORT_PERIOD_COPY[mode];
  const tagged = aggregate.tags.map((tag) => ({
    label: formatTagLabel(tag.tag, locale),
    total: tag.total,
    values: sumBreakdownValues(tag.sources, mode, weekStart)
  }));
  const overview = [
    `**${formatNumber(aggregate.noteCount)} of ${formatNumber(periodDayCount(aggregate.bounds))} days**`,
    `**${formatNumber(aggregate.words)} ${aggregate.words === 1 ? "word" : "words"}**`
  ];
  if (aggregate.totalCheckboxes > 0) {
    overview.push(
      `**${formatNumber(aggregate.completedCheckboxes)} of ${formatNumber(aggregate.totalCheckboxes)} checked**`
    );
  }
  const lines = ["## At a glance", "", overview.join(" · ")];
  if (tagged.length > 0) {
    const tallies = tagged
      .map((tag) => `${tag.label} ${formatNumber(tag.total)}`)
      .join(" · ");
    lines.push("", `**Tallies:** ${tallies}`);
  }
  const mostWriting = aggregate.wordSources.reduce<BreakdownSource | null>((best, source) => {
    if (best === null || source.value > best.value) return source;
    return best;
  }, null);
  if (mostWriting) {
    const label = formatBreakdownDay(mostWriting.date, locale);
    const words = `${formatNumber(mostWriting.value)} ${mostWriting.value === 1 ? "word" : "words"}`;
    lines.push("", `**Most writing:** ${breakdownLabel(label, mostWriting.path)} · ${words}`);
  }
  const periods = buildBreakdownRows(
    aggregate.noteSources,
    mode,
    aggregate.bounds,
    weekStart,
    locale
  );
  const words = sumBreakdownValues(aggregate.wordSources, mode, weekStart);
  const checked = sumBreakdownValues(aggregate.checkboxSources, mode, weekStart);
  if (periods.length > 0) {
    const includeChecked = aggregate.totalCheckboxes > 0;
    const header = [periodCopy.column, "Daily notes", "Words"];
    const alignment = ["---", "---:", "---:"];
    if (includeChecked) {
      header.push("Checked items");
      alignment.push("---:");
    }
    lines.push(
      "",
      `## ${periodCopy.heading}`,
      "",
      `| ${header.join(" | ")} |`,
      `| ${alignment.join(" | ")} |`
    );
    for (const period of periods) {
      const values = [
        breakdownLabel(period.label, period.path, true),
        formatNumber(period.value),
        formatNumber(words.get(period.key) ?? 0)
      ];
      if (includeChecked) values.push(formatNumber(checked.get(period.key) ?? 0));
      lines.push(`| ${values.join(" | ")} |`);
    }
    const tallyColumns = tagged.filter((tag) => tag.values.size > 0);
    if (tallyColumns.length > 0) {
      const tallyHeader = [periodCopy.column, ...tallyColumns.map((tag) => tag.label)];
      const tallyAlignment = ["---", ...tallyColumns.map(() => "---:")];
      lines.push(
        "",
        `## ${periodCopy.tallyHeading}`,
        "",
        `| ${tallyHeader.join(" | ")} |`,
        `| ${tallyAlignment.join(" | ")} |`
      );
      for (const period of periods) {
        const values = [
          breakdownLabel(period.label, period.path, true),
          ...tallyColumns.map((tag) => tag.values.has(period.key)
            ? formatNumber(tag.values.get(period.key) ?? 0)
            : "—")
        ];
        lines.push(`| ${values.join(" | ")} |`);
      }
    }
  }
  lines.push("", GENERATED_SUMMARY_MARKER, "");

  return {
    folder,
    path: joinVaultPath(folder, filename),
    content: lines.join("\n")
  };
}
